replicaCount: 1

image:
  repository: myapp
  tag: latest
  pullPolicy: ifNotPresent

service:
  port: 3000

ingress:
  enabled: true
  className: nginx
  host: myapp
  path: /
  pathType: Prefix

  name: "David"

  namespace: myapp