apiVersion: apps/v1
kind: Deployment
metadata:
    name: myapp
    namespace: {{.Values.namespace}}
spec:
    replicas: {{ .Values.replicaCount}}
selector:
    matchLabels:
        app: myapp
template:
    metadata:
        labels:
            app: myapp
    spec:
        containers:
            - name: myapp
              image: {{ .Values.image.repository}} : {{ .Values.image.tag}}
              imagePullPolicy: {{ .Values.image.imagePullPolicy}}
              ports:
                - containerPort: 3000
            env:
               - name: NAME
                 value: {{ .Values.name}}
            livenessProbe:
                httpGet:
                path: /
                 port: 3000
             initialDelaySeconds: 5
             periodSeconds: 10